# Generated by Django 5.2.4 on 2025-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_buffetitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="id_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
