# Generated by Django 5.2.4 on 2025-08-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_spicy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="subtitle",
            field=models.TextField(blank=True, default=""),
        ),
    ]
