# Generated by Django 5.2.4 on 2025-08-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_menuitem_is_spicy_menuitem_subtitle"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitchenCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="KitchenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("is_spicy", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurant.kitchencategory",
                    ),
                ),
            ],
            options={
                "db_table": "MenuItem",
                "ordering": ["category", "id_number"],
            },
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
