# Generated by Django 5.2.4 on 2025-08-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_kitchencategory_kitchenitem_delete_menuitem"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="kitchenitem",
            table=None,
        ),
    ]
