# Generated by Django 5.2.4 on 2025-08-13 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_kitchenitem_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuffetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name="kitchenitem",
            options={"ordering": ["category", "id"]},
        ),
        migrations.AlterField(
            model_name="buffetitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="restaurant.buffetcategory",
            ),
        ),
    ]
